cfg:
  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    normalize: per_feature
    window_size: 0.02
    sample_rate: 16000
    window_stride: 0.01
    window: hann
    features: 64
    n_fft: 512
    frame_splicing: 1
    dither: 1.0e-05
    stft_conv: false
  spec_augment:
    _target_: nemo.collections.asr.modules.SpectrogramAugmentation
    rect_freq: 50
    rect_masks: 5
    rect_time: 120
  encoder:
    _target_: nemo.collections.asr.modules.ConvASREncoder
    feat_in: 64
    activation: relu
    conv_mask: true
    jasper:
    - filters: 256
      repeat: 1
      kernel:
      - 33
      stride:
      - 2
      dilation:
      - 1
      dropout: 0.0
      residual: false
      separable: true
    - filters: 256
      repeat: 5
      kernel:
      - 33
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: true
      separable: true
    - filters: 256
      repeat: 5
      kernel:
      - 33
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: true
      separable: true
    - filters: 256
      repeat: 5
      kernel:
      - 33
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: true
      separable: true
    - filters: 256
      repeat: 5
      kernel:
      - 39
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: true
      separable: true
    - filters: 256
      repeat: 5
      kernel:
      - 39
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: true
      separable: true
    - filters: 256
      repeat: 5
      kernel:
      - 39
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: true
      separable: true
    - filters: 512
      repeat: 5
      kernel:
      - 51
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: true
      separable: true
    - filters: 512
      repeat: 5
      kernel:
      - 51
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: true
      separable: true
    - filters: 512
      repeat: 5
      kernel:
      - 51
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: true
      separable: true
    - filters: 512
      repeat: 5
      kernel:
      - 63
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: true
      separable: true
    - filters: 512
      repeat: 5
      kernel:
      - 63
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: true
      separable: true
    - filters: 512
      repeat: 5
      kernel:
      - 63
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: true
      separable: true
    - filters: 512
      repeat: 5
      kernel:
      - 75
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: true
      separable: true
    - filters: 512
      repeat: 5
      kernel:
      - 75
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: true
      separable: true
    - filters: 512
      repeat: 5
      kernel:
      - 75
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: true
      separable: true
    - filters: 512
      repeat: 1
      kernel:
      - 87
      stride:
      - 1
      dilation:
      - 2
      dropout: 0.0
      residual: false
      separable: true
    - filters: 1024
      repeat: 1
      kernel:
      - 1
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: false
  decoder:
    _target_: nemo.collections.asr.modules.ConvASRDecoder
    feat_in: 1024
    num_classes: 38
    vocabulary:
    - ' '
    - a
    - b
    - c
    - d
    - e
    - f
    - g
    - h
    - i
    - j
    - k
    - l
    - m
    - 'n'
    - o
    - p
    - q
    - r
    - s
    - t
    - u
    - v
    - w
    - x
    - 'y'
    - z
    - ''''
    - '!'
    - á
    - é
    - í
    - ñ
    - ó
    - ú
    - ü
    - ¿
    - ¡
  optim:
    name: novograd
    lr: 0.001
    betas:
    - 0.8
    - 0.5
    weight_decay: 0.001
    sched:
      name: CosineAnnealing
      warmup_steps: null
      warmup_ratio: null
      min_lr: 0.0
      last_epoch: -1
  target: nemo.collections.asr.models.ctc_models.EncDecCTCModel
  nemo_version: 1.7.0
  train_ds:
    manifest_filepath: ./data/manifests/train.json
    sample_rate: 16000
    labels:
    - ' '
    - a
    - b
    - c
    - d
    - e
    - f
    - g
    - h
    - i
    - j
    - k
    - l
    - m
    - 'n'
    - o
    - p
    - q
    - r
    - s
    - t
    - u
    - v
    - w
    - x
    - 'y'
    - z
    - ''''
    batch_size: 32
    trim_silence: true
    max_duration: 16.7
    shuffle: true
    is_tarred: false
    tarred_audio_filepaths: null
    tarred_shard_strategy: scatter
  validation_ds:
    manifest_filepath: ./data/manifests/test.json
    sample_rate: 16000
    labels:
    - ' '
    - a
    - b
    - c
    - d
    - e
    - f
    - g
    - h
    - i
    - j
    - k
    - l
    - m
    - 'n'
    - o
    - p
    - q
    - r
    - s
    - t
    - u
    - v
    - w
    - x
    - 'y'
    - z
    - ''''
    batch_size: 32
    shuffle: false
